cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='CartAdd'),
    url(r'^$', views.cart_detail, name='CartDetail'),
]

hardrock/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hardrock'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^order/', include('orders.urls', namespace='orders')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='AdminOrderDetail')
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.productlist, name='ProductList'),
    url(r'^deliver/$', views.deliver, name='deliver'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.productlist, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.productdetail, name='ProductDetail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Кількість ')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@csrf_exempt
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/back.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Ваш кошик
{% endblock %}
{% block content %}
    <h1>Таблиця замолвень</h1>
    <table class="cart table">
        <thead class="thead-light">
        <tr>
            <th scope="col">Зображення</th>
            <th scope="col">Товар</th>
            <th scope="col">Кількість</th>
            <th scope="col">Ціна</th>
            <th scope="col">Повна ціна</th>
            <th scope="col">Видалити</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" alt="" class="prod-img"/>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="Оновити">
                        </form>
                    </td>
                    <td class="num">{{ item.price }} грн.</td>
                    <td class="num">{{ item.total_price }} грн.</td>
                    <td>
                        <a href="{% url "cart:CartRemove" product.id %}">
                            <img src="{% static 'img/general/Delete.png' %}" alt="Видалити" class="delete-img"/>
                        </a>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Загальна</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }} грн.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:ProductList" %}" class="btn cart-btn">Продовжити покупки</a>
        <a href="{% url "orders:OrderCreate" %}" class="btn cart-btn">Оформити замовлення</a>
    </p>
{% endblock %}

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Ваш кошик
{% endblock %}
{% block content %}
    <div class="detail-table">
        <h1>Таблиця замолвень</h1>
        <table class="cart table">
            <thead align="right" class="thead-light">
            <tr>
{#                <th scope="col">Зображення</th>#}
                <th scope="col">Товар</th>
{#                <th scope="col">Кількість</th>#}
{#                <th scope="col">Ціна(1шт.)</th>#}
                <th scope="col">Повна ціна</th>
                <th scope="col">Видалити</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
{#                        <td>#}
{#                            <a href="{{ product.get_absolute_url }}">#}
{#                                <img src="{{ product.image.url }}" alt="" class="prod-img"/>#}
{#                            </a>#}
{#                        </td>#}
                        <td>{{ product.name }}</td>
{#                        <td>#}
{#                            <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">#}
{#                                {{ item.update_quantity_form.quantity }}#}
{#                                {{ item.update_quantity_form.update }}#}
{#                                {% csrf_token %}#}
{#                                <input type="submit" value="Оновити">#}
{#                            </form>#}
{#                        </td>#}
{#                        <td class="num">{{ item.price }} грн.</td>#}
                        <td class="num">{{ item.total_price }} грн.</td>
                        <td>
                            <a href="{% url "cart:CartRemove" product.id %}">
                                <img src="{% static 'img/general/Delete.png' %}" alt="Видалити" class="delete-img"/>
                            </a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Загальна</td>
                <td colspan="1"></td>
                <td>{{ cart.get_total_price }} грн.</td>
            </tr>
            </tbody>
        </table>
        <p class="text-center">
            <a href="{% url "shop:ProductList" %}" class="btn cart-btn">Продовжити покупки</a>
            <a href="{% url "orders:OrderCreate" %}" class="btn cart-btn">Оформити замовлення</a>
        </p>
    </div>

{% endblock %}