cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='CartAdd'),
    url(r'^$', views.cart_detail, name='CartDetail'),
]

hardrock/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hardrock'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^order/', include('orders.urls', namespace='orders')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.productlist, name='ProductList'),
    url(r'^deliver/$', views.deliver, name='deliver'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.productlist, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.productdetail, name='ProductDetail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=32,
        db_index=True
    )
    slug = models.SlugField(
        max_length=32,
        db_index=True,
        unique=True
    )

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        verbose_name='Категорія'
    )
    name = models.CharField(
        max_length=256,
        db_index=True,
        verbose_name='Назва'
    )
    slug = models.SlugField(
        max_length=256,
        db_index=True
    )
    image = models.ImageField(
        upload_to='prod_img/',
        blank=True,
        verbose_name='Зображення'
    )
    desc = models.TextField(
        blank=True,
        verbose_name='Опис'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Ціна'
    )
    stock = models.PositiveIntegerField(
        verbose_name='Запас'
    )
    available = models.BooleanField(
        default=True,
        verbose_name='Наявність'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Створено')
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Оновлено')

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def deliver(request):
    return render(request, 'other/delivery.html')


def contacts(request):
    return render(request, 'other/contacts.html')


def productlist(request, category_slug=None):
    template = 'shop/product/list.html'
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    page = request.GET.get('page')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sort_products = products.filter(category=category)
        paginator = Paginator(sort_products, 8)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
    else:
        paginator = Paginator(products, 8)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'page': page
    }
    return render(request, template, context)


def productdetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render_to_response('shop/product/detail.html',
                              {'product': product,
                               'cart_product_form': cart_product_form})

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=cyrillic" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicons.png' %}">
</head>
<body>
<div class="wrapper">
    <section id="header">
        {% include 'shop/header.html' %}
    </section>
    <section id="content row" class="container">
        {% block content %}{% endblock %}
    </section>
</div>

{% include 'shop/footer.html' %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/shop/footer.html
{% load static %}

<footer id="myFooter">
    <div class="container">
        <ul>
            <li><a href="{% url 'shop:ProductList' %}">Головна</a></li>
            <li><a href="{% url 'shop:deliver' %}">Доставка</a></li>
            <li><a href="{% url 'shop:contacts' %}">Контакти</a></li>
        </ul>
        <p class="footer-copyright">© {% now "Y" %} Тестовий сайт by <a href="https://github.com/rudiq4">rudiq4</a></p>
    </div>
    <div class="footer-social">
        <a href="#" class="social-icons"><i class="fa fa-facebook"></i></a>
        <a href="#" class="social-icons"><i class="fa fa-instagram"></i></a>
        <a href="#" class="social-icons"><i class="fa fa-twitter"></i></a>
    </div>
</footer>

templates/shop/header.html
{% load static %}

<header>
    <div class="top_bar">
        <div class="container">
            <div class="col-sm-6">
                <ul class="social">
                    <li><a target="_blank" href="#"><i class="fa fa-facebook text-white"></i></a>
                    </li>
                    <li><a target="_blank" href="#"><i class="fa fa-instagram text-white"></i></a>
                    </li>
                    <li><a target="_blank" href="#"><i class="fa fa-twitter text-white"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-6">
                <ul class="rightc">
                    <li><i class="fa fa-phone"></i> +38-066-888-88-88</li>
                    <li><i class="fa fa-cart-plus"></i>
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                Ваш кошик:
                                <a href="{% url "cart:CartDetail" %}">
                                    {{ total_items }} тов. {{ cart.get_total_price }} грн.
                                </a>
                            {% else %}
                                Кошик пустий
                            {% endif %}
                        {% endwith %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'shop:ProductList' %}"><img
                        src="{% static 'img/general/logo.jpg' %}" class="logo-img"></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'shop:ProductList' %}">Головна</a></li>
                    <li><a href="{% url 'shop:deliver' %}">Доставка</a></li>
                    <li><a href="{% url 'shop:contacts' %}">Контакти</a></li>
                </ul>
            </div>
        </div>
    </nav>

</header>

templates/shop/paginator.html
{% load static %}


<nav aria-label="Page navigation">
    {% if page.has_other_pages %}
        <ul class="pagination">
            {% if page.has.previous %}
                <li><a aria-label="Previous" href="
                ?page={{ page.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <li class="disabled"><span>&laquo;</span>
            {% endif %}
            {% for pages in page.paginator.page_range %}
                {% if page.number == pages %}
                    <li class="active"><span>{{ pages }}<span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ pages }}">{{ pages }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li><a href="?page={{ page.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
</nav>